# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch

import torch
random_tensor=torch.rand(7,7)
random_tensor
# Create random tensor


tensor([[0.6073, 0.7751, 0.7117, 0.9953, 0.2455, 0.0127, 0.6945],
        [0.2212, 0.5519, 0.4843, 0.2804, 0.9959, 0.1477, 0.7456],
        [0.0634, 0.7987, 0.8181, 0.9520, 0.1293, 0.6025, 0.3404],
        [0.2733, 0.3949, 0.1415, 0.4905, 0.9635, 0.4833, 0.4536],
        [0.7643, 0.3570, 0.1178, 0.6791, 0.1676, 0.0017, 0.9643],
        [0.1546, 0.0865, 0.8304, 0.0943, 0.0049, 0.0605, 0.4283],
        [0.6821, 0.5045, 0.9395, 0.6503, 0.9174, 0.3958, 0.3227]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
random_tensor2=torch.rand(7,2)
random_tensor2
# Perform matrix multiplication
tensor_mat=torch.matmul(random_tensor,random_tensor2)
random_tensor2,tensor_mat

(tensor([[0.8328, 0.6112],
         [0.4139, 0.3309],
         [0.1789, 0.4995],
         [0.2736, 0.9105],
         [0.5211, 0.4165],
         [0.8150, 0.0311],
         [0.1969, 0.7245]]),
 tensor([[1.5013, 2.4952],
         [1.3622, 1.7746],
         [1.4157, 1.8976],
         [1.5359, 1.5598],
         [1.2698, 2.0308],
         [0.4751, 0.9380],
         [1.9871, 2.2734]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)


# Create two random tensors
tensor_1=torch.rand(1,7)
torch.manual_seed(RANDOM_SEED)
tensor_2=torch.rand(7,1)
tensor3=torch.matmul(tensor_1,tensor_2)
tensor_1,tensor_2,tensor3


# Matrix multiply tensors


(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]]),
 tensor([[0.8823],
         [0.9150],
         [0.3829],
         [0.9593],
         [0.3904],
         [0.6009],
         [0.2566]]),
 tensor([[3.2618]]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)
  print("Gpu is available")
else:
  print("Gpu is not available")

Gpu is available



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
  rand1=torch.rand(2,3).to("cuda")
  rand2=torch.rand(3,2).to("cuda")
else:
  print('Gpu is not available')
# Create two random tensors on GPU
rand1,rand2

(tensor([[0.0753, 0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779]], device='cuda:0'),
 tensor([[0.9040, 0.5547],
         [0.3423, 0.6343],
         [0.3644, 0.7104]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
tensor_c=torch.matmul(rand1,rand2)
tensor_c

tensor([[0.5839, 1.0181],
        [0.7928, 1.1110]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
tensor_c.max(),tensor_c.min()
# Find min


(tensor(1.1110, device='cuda:0'), tensor(0.5839, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
tensor_c.argmax(),tensor_c.argmin()


# Find arg min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed

if torch.cuda.is_available():
  torch.cuda.manual_seed(7)
# Create random tensor

random_t1=torch.rand(2,2)
random_t1.shape,random_t1
print(random_t1)
print("dimensions before:")
print(random_t1.dim())
random_t2=random_t1.squeeze()
print("dimenssion after:")
random_t1.dim()
print(random_t2)

tensor([[0.1371, 0.5117],
        [0.1585, 0.0758]])
dimensions before:
2
dimenssion after:
tensor([[0.1371, 0.5117],
        [0.1585, 0.0758]])
