In [ ]:
#Pytorch fucndamentals
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


2.3.1+cu121


In [ ]:
#Introduction to tensors
#scalar is zero dimension tensor
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX=torch.tensor([[7,4],[4,5]])
MATRIX

tensor([[7, 4],
        [4, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#RANDOM TENSORS


# random tensors are important because many neural networks learn is that they start with tensors full of random number then adjust those random numbers to better to represent data


In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9018, 0.1664, 0.1628, 0.5219],
        [0.1844, 0.7920, 0.6925, 0.9283],
        [0.6348, 0.7858, 0.2550, 0.8310]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor2=torch.rand(3,10,6)
random_tensor2

tensor([[[0.6454, 0.6784, 0.1776, 0.2097, 0.9739, 0.6151],
         [0.7198, 0.8174, 0.8734, 0.8030, 0.4006, 0.3093],
         [0.3207, 0.3605, 0.8716, 0.4360, 0.6353, 0.4626],
         [0.6563, 0.1223, 0.1562, 0.7824, 0.3821, 0.9430],
         [0.4810, 0.8891, 0.3903, 0.4985, 0.4276, 0.6158],
         [0.7456, 0.5279, 0.9629, 0.5917, 0.4975, 0.0480],
         [0.9059, 0.0928, 0.8324, 0.6934, 0.6079, 0.2661],
         [0.0458, 0.8621, 0.0476, 0.9164, 0.4174, 0.4886],
         [0.7186, 0.7219, 0.2116, 0.1161, 0.5033, 0.9449],
         [0.8721, 0.6109, 0.2577, 0.3048, 0.9816, 0.6305]],

        [[0.5007, 0.3614, 0.1491, 0.8550, 0.5812, 0.3454],
         [0.9710, 0.8311, 0.9346, 0.3538, 0.5969, 0.0067],
         [0.1100, 0.7591, 0.9166, 0.8748, 0.5254, 0.6125],
         [0.9504, 0.9276, 0.7545, 0.1458, 0.5647, 0.9071],
         [0.8448, 0.0444, 0.3297, 0.0925, 0.8924, 0.2902],
         [0.3785, 0.8118, 0.6411, 0.2926, 0.4331, 0.3220],
         [0.2905, 0.1491, 0.0985, 0.4670, 0.9825, 0.21

In [ ]:
#create random tensor with simar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
#zeroes and ones tensor
zeroes=torch.zeros((3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

Getting information from tensor
1)Tensor is not right datatype=to get datatyoe use tensor.dtype
2)Tensors are not right shape
3)tensor is not right device,to get tensor from device tensor.device

In [ ]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1389, 0.4612, 0.3513, 0.2683],
        [0.3960, 0.7521, 0.6783, 0.2456],
        [0.9260, 0.9395, 0.0531, 0.9286]])

In [ ]:

some_tensor.size()


torch.Size([3, 4])

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
some_tensor.device

device(type='cpu')

In [ ]:
#Manipulating tensors
''' tensor operation include
1)addtion
2)sub
3)MULTIPLICATION -element vise
4)Division
5)Matrix multiplication



'''

' tensor operation include\n1)addtion\n2)sub\n3)MULTIPLICATION -element vise\n4)Division\n5)Matrix multiplication\n\n\n\n'

In [ ]:
tensor=torch.tensor([1,2,3])
tensor  + 10


tensor([11, 12, 13])

In [ ]:
tensor*10


tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#try pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
'''
Two ways of multiplication in neural network
Matrix multiplication(dot product)
element wise multiplication



'''

'\nTwo ways of multiplication in neural network\nMatrix multiplication(dot product)\nelement wise multiplication\n\n\n\n'

In [ ]:
tensor * tensor


tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)   #1*1+2*2+3*3

tensor(14)

One of the most common errors in deep learning is shape error
They are main two rules that performing matrix multiplication to satisfy
1)inner dimensions must be same
(3,2)*(3,2) wont work
(2,3)*(3,2) will work
(3,2)*(2,3) will work
2) THe resulting matrix has shape of outer dimensions


In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5281, 0.9587, 0.6218],
        [0.4680, 0.7129, 0.5144],
        [0.4933, 0.5552, 0.4896]])

In [ ]:
''' To fix out tensor shape issue we can manipulate the shape of our tensors using transpose'''
tensor.T




<ipython-input-39-377ce62fd02c>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
  tensor.T


tensor([1, 2, 3])

In [ ]:
tens=torch.tensor([[1,2,3],[4,5,6],[7,8,9],[5,6,7]])
tens.shape

torch.Size([4, 3])

In [ ]:
tens.T

tensor([[1, 4, 7, 5],
        [2, 5, 8, 6],
        [3, 6, 9, 7]])

Finding min max mean sum and tensor aggregation


In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
x.sum()

tensor(450)

Finding positional min max


In [ ]:
x.argmin()

tensor(0)

Find position in tensor that has maximum value with argmax

In [ ]:
x.argmax()

tensor(9)

Reshaping stacking squeezing and unsqueezing tensors
view-return view of an input tensor of certain shape but keep the same memory as orginal tensor


stacking-combine multiple tensors on top of each other(vstack) or side by side (hstack)
Squeeze-removes all 1 dimension from a tensor
Unsqueeze-add a 1 dimension to target tensor
Permute-Return a view of input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped2=x.reshape(9,1)
x_reshaped2

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

#stack tensor on top of each other


In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

torch.squeeze returns all single dimensions from a target tensor

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.unsqueeze(dim=0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
#torch.permute -change the dimensions as per order
x_original=torch.rand(size=(224,224,3))
x_original.shape


torch.Size([224, 224, 3])

In [ ]:
x_permuted=x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

Indexing selecting from tensors

In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x.dim()

3

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0][0][:]

tensor([1, 2, 3])

Pytorch tensors and Numpy
Numpy is popular scientific Python computing library
Pytorch has functionality to interact with it
Data in Numpy to Pytorch tensor
torch.from_numpy(ndarray)
Pytorch tensor Numpy torch.Tensor.numpy()

In [ ]:
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
#from converting numpy to tensor ,tensor gets default datatype float64
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

Pytorch reproducibility
(trying to take random out of random)
In short how a neural network
start with random number->tensor operation->updata random number to try and make them better representation of data
To reduce randomness in neural network and pytorch comes with concept of random seed



In [ ]:
#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
random_tensor_C==random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Running tensor and pytorch objects on the GPUS(and making better faster computations)
1) Getting GPU
Easiest using google collab for free GPU
2)Google collab pro
3) using your own GPU require investestments of purchasing GPU
Tim Dettmers which GPU too get for deep learning
4)Using cloud computing -GCP aws azure
rent computers on cloud
FOr  2,3 Pytorch +GPU drive CUDa setup pytorch documentation


In [ ]:
#check for  gpu access with pytorch
torch.cuda.is_available()

True

In [ ]:
#Set up agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

In [ ]:
'''
The reason we want our tensors/models on the GPU is because using results in faster computations





'''
tensor=torch.tensor([1,2,3],device="cpu")
print(tensor,tensor.device)




tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to gpu(if available0)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#NUMPY only works on cpu
#moving tensors back to cpu
#if tensor is on GPU ,cant tranform it to Numpy
#first set it to cpu
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
random_tensor=torch.rand(7,7)
random_tensor,random_tensor.shape

(tensor([[0.2297, 0.9545, 0.6099, 0.5643, 0.0594, 0.7099, 0.4250],
         [0.2709, 0.9295, 0.6115, 0.2234, 0.2469, 0.4761, 0.7792],
         [0.3722, 0.2147, 0.3288, 0.1265, 0.6783, 0.8870, 0.0293],
         [0.6161, 0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870],
         [0.4121, 0.3676, 0.5535, 0.4117, 0.3510, 0.8196, 0.9297],
         [0.4505, 0.3881, 0.5073, 0.4701, 0.6202, 0.6401, 0.0459],
         [0.3155, 0.9211, 0.6948, 0.4751, 0.1985, 0.1941, 0.0521]]),
 torch.Size([7, 7]))